### ISSUE TITLE
icon for lilyplayer

### ISSUE THREAD

**Issue by somratking420** [s-d-m/lilyplayer#1]
Hi @s-d-m , I am a graphic designer, I want to help you in graphic design.

After I review your project, your app is very good. Therefore I suggest a new logo and icon for you. If you want it, I will design it for you and it's free.

**Comment by s-d-m** [comment]
Hi Somrat,

Thanks for proposing that. The app is far away from being production
ready and I don't think I will invest (much) more time on it. But
nothing prevents you from forking it and making a logo if you fancy.

Cheers

**Comment by somratking420** [comment]
do not take the logo ,sir?
